-- CREATE DATABASE IF NOT EXISTS moviedb;
-- USE moviedb;

CREATE TABLE IF NOT EXISTS TBL_USER (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(120) NOT NULL,
  email varchar(120) NOT NULL,
  password varchar(20) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TBL_BOOKMARK (
  id int(11) NOT NULL AUTO_INCREMENT,
  user_id int(11) NOT NULL,
  movie_id varchar(20) NOT NULL,
  PRIMARY KEY (id),
  KEY fk_user (user_id),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES tbl_user(id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;